var annotated_dup =
[
    [ "SDbConvertOptions", "struct_s_db_convert_options.html", "struct_s_db_convert_options" ],
    [ "SDbCopyOptions", "struct_s_db_copy_options.html", "struct_s_db_copy_options" ],
    [ "SDbExportOptions", "struct_s_db_export_options.html", "struct_s_db_export_options" ],
    [ "T3DPoint", "struct_t3_d_point.html", "struct_t3_d_point" ],
    [ "T3DTransform", "class_t3_d_transform.html", "class_t3_d_transform" ],
    [ "TAboutBox", "class_t_about_box.html", "class_t_about_box" ],
    [ "TCube", "class_t_cube.html", "class_t_cube" ],
    [ "TDbConvertDlg", "class_t_db_convert_dlg.html", "class_t_db_convert_dlg" ],
    [ "TDbCopyDlg", "class_t_db_copy_dlg.html", "class_t_db_copy_dlg" ],
    [ "TDbExportDialog", "class_t_db_export_dialog.html", "class_t_db_export_dialog" ],
    [ "TDbInfoDialog", "class_t_db_info_dialog.html", "class_t_db_info_dialog" ],
    [ "TDbLabeledImages", "class_t_db_labeled_images.html", "class_t_db_labeled_images" ],
    [ "TDbSplitDlg", "class_t_db_split_dlg.html", "class_t_db_split_dlg" ],
    [ "TDetectorForm", "class_t_detector_form.html", "class_t_detector_form" ],
    [ "TDictionaryDialog", "class_t_dictionary_dialog.html", "class_t_dictionary_dialog" ],
    [ "TEngineErrDlg", "class_t_engine_err_dlg.html", "class_t_engine_err_dlg" ],
    [ "TEngineViewForm", "class_t_engine_view_form.html", "class_t_engine_view_form" ],
    [ "TFilterDlg", "class_t_filter_dlg.html", "class_t_filter_dlg" ],
    [ "TForm1", "class_t_form1.html", "class_t_form1" ],
    [ "TForm3", "class_t_form3.html", "class_t_form3" ],
    [ "TFragmentForm", "class_t_fragment_form.html", "class_t_fragment_form" ],
    [ "TGaussFilterDlg", "class_t_gauss_filter_dlg.html", "class_t_gauss_filter_dlg" ],
    [ "THsv2DForm", "class_t_hsv2_d_form.html", "class_t_hsv2_d_form" ],
    [ "TLFProject", "class_t_l_f_project.html", "class_t_l_f_project" ],
    [ "TLongProcDlg", "class_t_long_proc_dlg.html", "class_t_long_proc_dlg" ],
    [ "TMarkerIniParams", "class_t_marker_ini_params.html", "class_t_marker_ini_params" ],
    [ "TMedianFilterDlg", "class_t_median_filter_dlg.html", "class_t_median_filter_dlg" ],
    [ "TOKBottomDlg", "class_t_o_k_bottom_dlg.html", "class_t_o_k_bottom_dlg" ],
    [ "TPagesDlg", "class_t_pages_dlg.html", "class_t_pages_dlg" ],
    [ "TPhImageMarkTool", "class_t_ph_image_mark_tool.html", "class_t_ph_image_mark_tool" ],
    [ "TRectToolForm", "class_t_rect_tool_form.html", "class_t_rect_tool_form" ],
    [ "TResizeDlg", "class_t_resize_dlg.html", "class_t_resize_dlg" ],
    [ "TRotateDlg", "class_t_rotate_dlg.html", "class_t_rotate_dlg" ],
    [ "TTableForm", "class_t_table_form.html", "class_t_table_form" ],
    [ "TVersionInfo", "class_t_version_info.html", "class_t_version_info" ]
];